### ISSUE TITLE
Document configuration of Prometheus with MetalLB

### ISSUE THREAD

**Issue by danderson** [google/metallb#147]
**Is this a bug report or a feature request?**:

Feature request.

**What happened**:

A conversation in Slack reminded me that we don't really give any guidance on how to monitor MetalLB. The manifest comes with the automagic scrape annotations for Prometheus, but we cannot configure any alerting through this mechanism.

There are some obvious alerts that most MetalLB deployments should have, stuff like "BGP session down for >30min", "no ARP leader for >5min", ...

Currently every MetalLB user has to reinvent these configurations.

**What you expected to happen**:

The website should have a configuration subsection for "Here's the stuff you might want to add to your cluster Prometheus deployment."

**How to reproduce it (as minimally and precisely as possible)**:

Try to monitor the health of MetalLB with Prometheus.

**Comment by jpds** [comment]
Some alerts I've configured for Prometheus 2:

```
      - alert: MetalLBNoLeader
        expr: count(metallb_k8s_client_leadership_bool == 1) != 0
        for: 2m             
        annotations:                                                                 
          description: MetalLB has no leader                 
          summary: MetalLB has had no leader for the past 2 minutes.
      - alert: MetalLBConfigStale                       
        expr: metallb_k8s_client_config_stale_bool != 0               
        for: 2m                                                          
        annotations:                                     
          description: '{{ $labels.instance }}: MetalLB instance has stale configuration.'
          summary: '{{ $labels.instance }}: MetalLB stale configuration.'
```

**Comment by jpds** [comment]
Couple more:

```
      - alert: MetalLBUpdateErrors                      
        expr: metallb_k8s_client_update_errors_total != 0
        for: 2m        
        annotations:                                                                                       
          description: '{{ $labels.instance }}: MetalLB instance has encountered {{ value }} update errors.'
          summary: '{{ $labels.instance }}: MetalLB update errors.'
      - alert: MetalLBUsableAddressUtilisation                                                                                                                   
        expr: ((metallb_allocator_addresses_in_use_total / metallb_allocator_addresses_total) * 100) > 75
        for: 2m                                         
        annotations:          
          description: 'MetalLB usable address utilisation is currently at {{ value }}%.'
          summary: 'MetalLB address space utilisation alert.'
```

**Comment by jpds** [comment]
Potentially better query `expr` for the `MetalLBUsableAddressUtilisation` alert above:

```
(sum((metallb_allocator_addresses_in_use_total / metallb_allocator_addresses_total)) by (pool) / count(metallb_allocator_addresses_in_use_total) by (pool) * 100)
```

I don't have multiple pools in prod to test this with.

**Comment by jpds** [comment]
Another simple one:

```
      - alert: MetalLBNoUsableAddresses
        expr: metallb_allocator_addresses_total == 0
        annotations:
          description: 'MetalLB has no usable addresses.'
          summary: 'MetalLB no usable address space.'
```
