### ISSUE TITLE
role ...speaker can not list configmap after upgrade

### ISSUE THREAD

**Issue by miekg** [google/metallb#162]
**Is this a bug report or a feature request?**:

question.

**What happened**:

upgraded metallb to the latest version (master git) and it broke my setup. Logs are full off (I'm away from the cluster, so I'll have to make this up):
~~~
role `...:speaker` can not list configMaps in the metallb-system namespace
~~~

**What you expected to happen**:

not break

**How to reproduce it (as minimally and precisely as possible)**:

not sure

**Anything else we need to know?**:

I have edited to my manifest a bit, but the only differences are prometheus annotations and a few extra services I've added. 
Seems some `verb`s are something is missing or I glanced over a diff (had to leave the house in a rush).

Anyway filing here. I'l take a closer look this evening (UTC)

**Comment by danderson** [comment]
I very quickly rescanned the RBAC rules in the manifests, and... It should be working. The specific things are:
 - DaemonSet runs as the service account "speaker" in the "metallb-system" namespace
 - RoleBinding "config-watcher" in the "metallb-system" namespace binds that service account to role "config-watcher"
 - Role "config-watcher" in the "metallb-system" namespace grants get+list+watch on all configmaps in the "metallb-system" namespace.

First step would be to check if those objects are all in place (but they should be if you applied the manifest).

**Comment by miekg** [comment]
Can't figure what is different. :(
err is:
~~~
1 reflector.go:205] go.universe.tf/metallb/internal/k8s/k8s.go:249: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:metallb-system:speaker" cannot list configmaps in the namespace "metallb-system"
~~~

**Comment by miekg** [comment]
[metallb.yaml.txt](https://github.com/google/metallb/files/1712129/metallb.yaml.txt)

**Comment by danderson** [comment]
Found it: the role is missing one `-`:

Your config:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: metallb-system
  name: config-watcher
rules:
- apiGroups: [""]
  resourceNames: ["metallb-speaker"]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  # Allow creating events in the metallb-system namespace
  # so that watchers can post config errors.
  apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
```

Github manifest:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: metallb-system
  name: config-watcher
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- # Allow creating events in the metallb-system namespace
  # so that watchers can post config errors.
  apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
```

Note the `-` before the comment block... I suspect yaml parsing is eating the `-` somehow and borking everything... Try removing the comment and see if that applies the correct stuff?
