### ISSUE TITLE
Try to add Juniper vSRX and vMX to test-bgp-router

### ISSUE THREAD

**Issue by danderson** [google/metallb#22]
Juniper offers "trial" versions of the vSRX and vMX virtual routers. I think in this case trial version means the router will only run for a limited time before shutting down. That's not a deal-breaker for test environments! And it would be great to have interop testing with Juniper stacks.

One challenge is figuring out how to run the virtual appliances in minikube. They're heavy VM images, not containers, so we may have to wait for Kubevirt to work reliably in Minikube, or have separate documentation on how to set up a hybrid test environment with minikube + other VMs.

**Comment by halfa** [comment]
@danderson as mention in #5, I got MetalLB to speak to a a real Juniper MX. JunOS is a bit... _verbose_ about BGP Optional Parameters, and your parsing somehow failed on the chained options decode, specifically around https://github.com/google/metallb/blob/24be4736ccdc7bf234251afa9216a48427ed9b0b/internal/bgp/messages.go#L172-L174

The given error message is `[...] 28 trailing garbage bytes after capabilities`, which is very strange because JunOS correctly advertise a 30 bytes message:
```YAML
# BGP Open from MX to MetalLB
Border Gateway Protocol - OPEN Message
Marker: ffffffffffffffffffffffffffffffff
Length: 59
Type: OPEN Message (1)
Version: 4
My AS: -
Hold Time: 90
BGP Identifier: -
Optional Parameters Length: 30
Optional Parameters
  - Optional Parameter: Capability
        Parameter Type: Capability (2)
        Parameter Length: 6
        Capability: Multiprotocol extensions capability
        Type: Multiprotocol extensions capability (1)
        Length: 4
        AFI: IPv4 (1)
        Reserved: 00
        SAFI: Unicast (1)
  - Optional Parameter: Capability
    Parameter Type: Capability (2)
        Parameter Length: 2
        Capability: Route refresh capability (Cisco)
        Type: Route refresh capability (Cisco) (128)
        Length: 0
  - Optional Parameter: Capability
    Parameter Type: Capability (2)
        Parameter Length: 2
        Capability: Route refresh capability
        Type: Route refresh capability (2)
        Length: 0
        Optional Parameter: Capability
        Parameter Type: Capability (2)
        Parameter Length: 4
  - Capability: Graceful Restart capability
    Type: Graceful Restart capability (64)
        Length: 2
        [Expert Info (Chat/Request): Graceful Restart Capability supported in Helper mode
        only]
        [Graceful Restart Capability supported in Helper mode only]
        [Severity level: Chat]
        [Group: Request]
        Restart Timers: 0x0078
        0... .... .... .... = Restart: No
        .... 0000 0111 1000 = Time: 120
  - Optional Parameter: Capability
    Parameter Type: Capability (2)
        Parameter Length: 6
        Capability: Support for 4-octet AS number capability
        Type: Support for 4-octet AS number capability (65)
        Length: 4
        AS Number: -
```

My workaround ATM was to disable this check, but I'll try to investigate ASAP
