### ISSUE TITLE
LB-Service doesn't response after master shutdown

### ISSUE THREAD

**Issue by runam0K** [google/metallb#237]
**Is this a bug report or a feature request?**:
Bug?

**What happened**:
When I shut down my kubernetes-master, the loadbalancer-service isnt responding after about four minutes. Everything works before that time.

If I start the master again then I can access the service again.

Is this a normal behavior? How can I solve the problem?

**What you expected to happen**:
The service should continue to be accessible.

**How to reproduce it (as minimally and precisely as possible)**:
- Shut down master
- Wait for four minutes
- Service is not responsible anymore

**Anything else we need to know?**:
ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.42.20.80-10.42.20.90
```

LB Service:
```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-lb
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: ingress-nginx
```

**Environment**:
- MetalLB version: latest
- Kubernetes version: 1.10
- BGP router type/version:
- OS (e.g. from /etc/os-release): debian stretch
- Kernel (e.g. `uname -a`): 4.9.0-6-amd64
