### ISSUE TITLE
IP address sharing + externalTrafficPolicy: Local; exact same selector mixes traffic between pods

### ISSUE THREAD

**Issue by uablrek** [google/metallb#271]
**Is this a bug report or a feature request?**:

Bug

**What happened**:

The metallb [documentation](https://metallb.universe.tf/usage/#ip-address-sharing) states that if address sharing and `externalTrafficPolicy: Local` is combined the services must "have the *exact* same selector".

But the implementing pods must then also have the same selector or Kubernetes complains. However Kubernetes seem to regard the pods exactly equal and distributes traffic to all sevices with the shared ip (and the same selector) to all pods, regardless of which ports they serve.

Hence my two pods serving ports 22 and 5001 will get a mix of traffic to the ports and half the traffic is lost.

**What you expected to happen**:

Traffic to a service should be distributed to the pods implementing the service only.

**How to reproduce it (as minimally and precisely as possible)**:

I have 2 services and deployments;

```
apiVersion: v1
kind: Service
metadata:
  name: cgen
  annotations:
    metallb.universe.tf/allow-shared-ip: ekvm
spec:
  selector:
    app: ekvm
  ports:
  - port: 5001
  externalTrafficPolicy: Local
  loadBalancerIP: 10.0.0.2
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cgen-deployment
spec:
  selector:
    matchLabels:
      app: ekvm
  replicas: 4
  template:
    metadata:
      labels:
        app: ekvm
    spec:
      containers:
      - name: cgen
        image: example.com/cgen:0.0.1
        ports:
        - containerPort: 5001
```

and

```
apiVersion: v1
kind: Service
metadata:
  name: ekvm-busybox
  annotations:
    metallb.universe.tf/allow-shared-ip: ekvm
spec:
  selector:
    app: ekvm
  ports:
  - port: 1022
    name: ssh
    targetPort: 22
  externalTrafficPolicy: Local
  loadBalancerIP: 10.0.0.2
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekvm-busybox-deployment
spec:
  selector:
    matchLabels:
      app: ekvm
  replicas: 4
  template:
    metadata:
      labels:
        app: ekvm
    spec:
      containers:
      - name: ekvm-busybox
        image: example.com/ekvm-busybox:0.0.1
        ports:
        - containerPort: 22
          name: ssh
```

When started every other attempt to e.g. port 1022 will fail;

```
vm-201 ~ # ssh -p 1022 10.0.0.2 netstat -putan
dbclient: Caution, skipping hostkey check for 10.0.0.2

Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      35/dropbear
tcp        0      0 11.0.2.2:22             192.168.0.201:56530     ESTABLISHED 56/dropbear
tcp        0      0 :::80                   :::*                    LISTEN      28/inetd
tcp        0      0 :::22                   :::*                    LISTEN      35/dropbear
tcp        0      0 :::23                   :::*                    LISTEN      28/inetd
vm-201 ~ # ssh -p 1022 10.0.0.2 netstat -putan

dbclient: Connection to root@10.0.0.2:1022 exited: Connect failed: Connection refused
```

The source is preserved (`192.168.0.201`) as seen in the first attempt, so far so good. But the second attempt fails because it is routed to the *other* serving only port 5001.

I run proxy-mode=ipvs so it is quite easy to visualize the problem;

```
vm-003 ~ # ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  192.168.0.3:31374 rr
  -> 11.0.3.2:5001                Masq    1      0          0
  -> 11.0.3.3:5001                Masq    1      0          0
TCP  10.0.0.2:1022 rr
  -> 11.0.3.2:22                  Masq    1      0          0
  -> 11.0.3.3:22                  Masq    1      0          0
TCP  10.0.0.2:5001 rr
  -> 11.0.3.2:5001                Masq    1      0          0
  -> 11.0.3.3:5001                Masq    1      0          0
TCP  11.0.3.1:30919 rr
...
```

The loadBalancerIP `10.0.0.2` is distributed locally (good) but for port 1022 it is distributed to *both* local pods which is a bug IMO. Maybe not in `metallb` though.

**Anything else we need to know?**:

Actually I can't understand the restriction of *exact* the same selector.

By removing the [check](https://github.com/google/metallb/blob/d38ad1ef80188b6e5bcdb246cff72039d6d52e3a/internal/allocator/k8salloc/k8salloc.go#L28-L30) i can make it work perfectly the way I want it.

**Environment**:
- MetalLB version:
Built from source. commit; d38ad1ef80188b6e5bcdb246cff72039d6d52e3a
- Kubernetes version:
v1.10.5-beta
- BGP router type/version:
gobgp
- OS (e.g. from /etc/os-release):
Own busyBox based
- Kernel (e.g. `uname -a`):
`Linux vm-003 4.16.2 #2 SMP Mon Jun 11 16:02:46 CEST 2018 x86_64 GNU/Linux`
