### ISSUE TITLE
Cannot connect to Loadbalancer service when.

### ISSUE THREAD

**Issue by FerronN** [google/metallb#317]
**Is this a bug report or a feature request?**:
bug

**What happened**:
I've created two loadBalance service. When I connected to the pulbic ip of the service everything works fine. When I delete and recreate the deployment for the app the loadBalance service is supposed to loadBalance I can't connect anymore.

I've a workaround as follows:
Delete the speaker pods and it works again.

```
service yaml:
apiVersion: v1
kind: Service
metadata:
  name: teamspeak-tcp
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
    metallb.universe.tf/allow-shared-ip: teamspeak
spec:
  ports:
  - port: 10011
    targetPort: 10011
    name: file
    protocol: TCP
  - port: 30033
    targetPort: 30033
    name: query
    protocol: TCP
  selector:
    app: teamspeak-server
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: teamspeak-udp
  annotations:
    metallb.universe.tf/address-pool: production-public-ips
    metallb.universe.tf/allow-shared-ip: teamspeak
spec:
  ports:
  - port: 9987
    targetPort: 9987
    name: voice
    protocol: UDP
  selector:
    app: teamspeak-server
  type: LoadBalancer
```

**What you expected to happen**:
That I could connect to my service again after I recreated the deployment.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a deployment with some app
2. Setup a loadbalance service and attach it to the app label of the deployment
3. Check if the connection work trough the loadbalancer to the app
4. Delete the deployment of the app
5. Recreate the deployment of the app
6. Can't connect

**Anything else we need to know?**:
No that I can think of, but if you need something please ask

**Environment**:
- MetalLB version: 0.7.3
- Kubernetes version:  1.11.2
- BGP router type/version: layer2
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`):
