### ISSUE TITLE
pod running SSH keeps getting "broken pipe" after ~10 minutes

### ISSUE THREAD

**Issue by benwbooth** [google/metallb#377]
**Is this a bug report or a feature request?**:

bug report

**What happened**:

I'm running a StatefulSet with one pod that runs an SSH server. When I connect to the SSH server using a MetalLB static IP address, I keep getting disconnected with a "broken pipe" message after about 10 minutes. When I connect to the same SSH server over NodePort,  or connect to the container directly using kubectl exec -it, it doesn't disconnect. At first I thought it was a SSH configuration issue, but I don't get disconnected when connecting using NodePort. So I think it is an issue with the LoadBalancer breaking the connection after a certain amount of time.

**What you expected to happen**:

The session would not disconnect.

**How to reproduce it (as minimally and precisely as possible)**:

Here is my `metallb.yaml`:

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: layer2
      addresses:
      - 128.3.60.0/22
```

Here is my service file:
```
apiVersion: v1
kind: Service
metadata:
  name: torso-maple-ssh
  annotations:
    metallb.universe.tf/allow-shared-ip: torso
spec:
  loadBalancerIP: 128.3.61.86
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    name: torso-maple
  type: LoadBalancer
```

**Anything else we need to know?**:

Is there some configuration setting to use to prevent the LoadBalancer from timing out or disconnecting?

**Environment**:
- MetalLB version: 0.7.3
- Kubernetes version: 1.11.5
- BGP router type/version: using layer2 mode
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0-141-generic
