### ISSUE TITLE
Support per-node peering configurations

### ISSUE THREAD

**Issue by danderson** [google/metallb#52]
**Is this a bug report or a feature request?**:

feature request

**What happened**:

In #50 , @xnaveira describes a cluster architecture where k8s nodes are connected to different BGP-speaking switches. In that setup, MetalLB's peering configuration is not adequate, because the configuration specifies a single peering config for the entire cluster, but in Xavier's cluster, specific nodes can only peer with specific routers.

We should consider supporting, as an advanced configuration option, per-node peering configurations, so that Xavier's use case can Just Work without extra hacks required.

**Comment by jpiper** [comment]
Using the same syntax that's used for node affinity would probably be a good idea :)

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

Maybe something like...

```yaml
peers:
- my-asn: 64512
  peer-asn: 64512
  peer-address: 10.96.0.100
  affinity:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - host-1.mydomain.com
        - host-1.mydomain.com
- my-asn: 64512
  peer-asn: 64512
  peer-address: 10.96.0.101
  affinity:
    - matchExpressions:
      - key: my_custom_rack_label
        operator: In
        values:
        - rack1
        - rack2
address-pools:
- name: my-ip-space
  cidr:
  - 198.51.100.0/24
  advertisements:
  - localpref: 100
```
